### ISSUE TITLE
A request to review "list-t-libcurl"

### ISSUE THREAD

**Issue by nikita-volkov** [kkardzis/curlhs#3]
I've released a library, which abstracts over "curlhs" with a streaming interface. Could you please review it on the subject of whether I handle and release the resources properly?

https://github.com/nikita-volkov/list-t-libcurl/blob/master/library/ListT/Libcurl.hs

**Comment by kkardzis** [comment]
Firstly, I'm glad to see my library in use. Secondly, I'm not as advanced Haskeller, as I would like to be. My understanding of all those functional abstractions, interfaces etc. is far from great. But if I read your code correctly, the use of 'curlhs' seems correct. Despite this, I would like to draw your attention to two things.

First in the code:

```haskell
acquire = do
  h <- C.curl_easy_init
  C.curl_easy_setopt h [C.CURLOPT_FAILONERROR True]
  return h
```

`curl_easy_setopt` may throw an exception. It should never happen in the above case (it's only a flag set), but with some other libcurl options the exceptions are possible (not builtin feature / not enabled etc.) and acquired handle will leak unreleased then. With more advanced settings consider this:

```haskell
acquire = do
  bracketOnError (C.curl_easy_init) (C.curl_easy_cleanup) $ \h -> do
    C.curl_easy_setopt h [ ... ]
    return h
```

Second, more important remark concerns the `withlib` placement. The short explanation is this: `withlib` should be placed into `main`, directly or as close as possible, wrapping all uses of libcurl.

But why? `withlib` performs two things:

1. It loads/unloads libcurl shared object (libcurl.dll etc.). I don't know what is the performance cost of that operation, but I think it's not cheap enough, to loose it for every session. If that aspect is not important then of course it's possible to load/unload on demand, but look at the second point.

2. It does global initialization and cleanup of the library (`curl_global_init` / `curl_global_cleanup`). As stated in the documentation at http://curl.haxx.se/libcurl/c/libcurl.html and http://curl.haxx.se/libcurl/c/curl_global_init.html this operation is mandatory and it is not thread safe in addition. It probably concerns not the libcurl itself, but something deeper like ssl engine. I don't know for sure. But I think that in multithreaded Haskell it is highly possible that something may go wrong.

This defers the responsibility of using `withlib` to the user of your library or even later up to the application programmer. I know that it is not in the Haskell style, but it is the cost of using the explicit linking method and probably more the cost of using the foreign library at all. Haskell 'network' package has its 'withSocketsDo', 'curl' package its 'withCurlDo'. Many C libraries requires some form of global init/exit. I've been experimenting with a few (sdl, glfw, glut, fmod), and I don't have a good solution now.

**Comment by nikita-volkov** [comment]
Thanks for your review!

Concerning `withlib`, forcing the user to place it in `main` really does a great damage to the usability of the library. Even in the mentioned "network" package they're finally getting rid of that annoying `withSocketsDo` AFAIK. 

I think I have an idea of what we can do about it here. One only needs to load the "libcurl" shared object once per the whole application, right? So how about doing it globally with `unsafePerformIO` the same way I'm building a global pool in the referred module? 

I can even do the same in my library: https://github.com/nikita-volkov/list-t-libcurl/commit/ed0ce643762d0fd81262df9cd95aaa180ed1dc63. However, I suspect that unless `loadlib` is multicall-checked, this might cause conflicts with other libraries, which use "curlhs". It'd be trivial to update `loadlib` to fix such issue however.

**Comment by kkardzis** [comment]
Your solution with placing `loadlib` behind `unsafePerformIO` should be sufficient for most use cases. `loadlib` **is** multicall-checked, so it's not an issue to call it multiple times (even concurrently). And in case when there is no corresponding `freelib`, the library is freed by the operating system on program exit. Considering only loading/unloading of the library everything should be fine. So far so good.

My doubts comes rather from the libcurl initialization specifics. From the docs that I linked before:

> It isn't actually required that the functions be called at the beginning and end of the program -- that's just usually the easiest way to do it. It is required that the functions be called when no other thread in the program is running.

Computation wrapped in `unsafePerformIO` may be performed at any time. Is that such relevant in our case? I think it may be, but please read carefully the libcurl docs on the subject and decide for yourself.

**Comment by nikita-volkov** [comment]
Okay. Thanks! You've been very helpful!

**Comment by nikita-volkov** [comment]
BTW, what do you think about using `unsafePerformIO` to `loadlib` behind the scenes in the "curlhs" itself?

**Comment by kkardzis** [comment]
I was thinking about this some time ago, and I decided finally that I want to give some control of the loading process to users of the library. For now, I don't want to change this. Maybe someday.

I think that by making the loader implicit (load on first use), the `curl_global_init` / `curl_global_cleanup` API should be exposed. So the situation will not change.

**Comment by nikita-volkov** [comment]
A problem with the current API is that it makes the dependencies of "curlhs" likely to conflict. E.g., if my library gets used with some other library, which calls "freelib" or "withlib" on a concurrent thread, I expect some nasty and hardly trackable failures to appear.

**Comment by kkardzis** [comment]
The "curlhs" loader uses reference counting method, with a counter protected by an MVar. There will be no conflicts as long as anyone uses the loader correctly, and by the correct use I mean just that no one calls `freelib` without using `loadlib` at first. Try this example:

```haskell
module Main where

import Control.Concurrent
import Control.Exception
import Network.CURL720

curlGET xs =
  bracket (curl_easy_init) (curl_easy_cleanup) $ \curl -> do
    curl_easy_setopt curl [ CURLOPT_URL ("http://httpbin.org/get?id=" ++ xs) ]
    putStrLn ("Start #" ++ xs) >> curl_easy_perform curl

main = do
  withlib CURL720 (curlGET "1")
  withlib CURL720 $ do
    forkIO $ withlib CURL730 (curlGET "2")
    forkIO $ withlib CURL720 (curlGET "3")
  withlib CURL730 $ do
    forkIO $ withlib CURL730 (curlGET "4")
    forkIO $ withlib CURL720 (curlGET "5")
  threadDelay 5000000
```

But ok, let's forget about `loadlib`, `freelib` and `withlib` trio. Let's assume that there are only plain, ready to use "libcurl" calls, and among them mentioned `curl_global_init` and `curl_global_cleanup` with their requirements about thread safety. Does it really change something? Does it really help you with your library? Correct me if I'm wrong, but I don't think so.

The "libcurl" team introduced this global initialization for some reason, and there is nothing we can do about that. One more citation from the "libcurl" docs:

> There is a failsafe in libcurl that makes it usable in simple situations without you having to worry about the global constant environment at all: curl_easy_init sets up the environment itself if it hasn't been done yet. The resources it acquires to do so get released by the operating system automatically when the program exits.
>
> This failsafe feature exists mainly for backward compatibility because there was a time when the global functions didn't exist. Because it is sufficient only in the simplest of programs, it is not recommended for any program to rely on it.

How can I help you more?

**Comment by nikita-volkov** [comment]
> The "curlhs" loader uses reference counting method, with a counter protected by an MVar.

Good. I was going to suggest that as an alternative.

> Let's assume that there are only plain, ready to use "libcurl" calls, and among them mentioned curl_global_init and curl_global_cleanup with their requirements about thread safety. Does it really change something? Does it really help you with your library? Correct me if I'm wrong, but I don't think so.

Well, I hope you already understand my concern about the possible conflicts triggered by the shared state. I'm worried about some code absolutely unrelated to my library being able to bring it into a state of failure. This is a common problem in imperative languages, so their library authors don't worry about that much, but in Haskell such a behaviour of a library will simply catch users off guard, causing an extreme frustration.

With that said, I'm now concerned about what's gonna happen if somebody calls `curl_global_cleanup` concurrently, while my library is still working?

> The "libcurl" team introduced this global initialization for some reason, and there is nothing we can do about that.

Well, yes, but I doubt they had Haskell dependencies in mind. The library is written for the C language, which generally practices very different approaches, which most of us consider suboptimal at very least. So, IMO, even the binding libraries need to provide the bare minimum abstractions, which ensure a certain safety level. Don't get me wrong, I'm not criticising, I'm just making an argument that it's Okay for a binding library to introduce certain tweaks over the wrapped library.

---

So, to make it more precise, I'd like to rephrase my suggestion to the following: hide all the functions, which deal with the shared state. E.g., perform `loadlib` and `curl_global_init` behind the scenes and never use `curl_global_cleanup` and `freelib` at all.

**Comment by kkardzis** [comment]
I think you know how reference counting works, and therefore, that if there are no buggy parts in the program, then in case of your library, the "libcurl" will never be unloaded, even if another library will concurrently perform many load/free calls. I guess that your concerns comes down rather to a buggy situations, and that you suggest to try to eliminate the possibility of writing bad code by the users of "curlhs". For example the situation where in some part of the program someone calls `freelib` (and therefore `curl_global_cleanup`) to many times (more frees than loads). This is possible of course. In such case your library may fail unexpected (like the whole program). It's true.

Global shared state is always dangerous. And in the environment like Haskell, where users usually do not have to worry about such things, it is especially touchy subject. I've tried to make this part of the library as safe as possible, but not more.

It is possible to perform `loadlib` and `curl_global_init` behind the scenes like you sugest. The process of load/init will be performed on first use then and it will be irreversible, so no one can do something wrong. Almost... what about the "libcurl" requirement that this should be done on the main thread and when there is only that one thread in the program? From docs about `curl_global_init`:

> This function is not thread safe. You must not call it when any other thread in the program (i.e. a thread sharing the same memory) is running. This doesn't just mean no other thread that is using libcurl. Because curl_global_init calls functions of other libraries that are similarly thread unsafe, it could conflict with any other thread that uses these other libraries. 

Should I ignore that? I wouldn't like to give to users a sense of safety, when I can not guarantee it.

**Comment by nikita-volkov** [comment]
> Should I ignore that? I wouldn't like to give to users a sense of safety, when I can not guarantee it.

Okay. I get your concern. But even then it's still possible to protect from improper `freelib` usage by only exposing `loadlib`, which instead of reference counting will only just whether it's been called before to ensure that it's only called once. You can suggest to users to call it in the main thread in the docs then.

**Comment by kkardzis** [comment]
Yes, this may be the solution. Thanks for the discussion.

**Comment by nikita-volkov** [comment]
Thank you too.

**Comment by kkardzis** [comment]
I think that this patch may interest you: 3babfea992712ec92df5b7fcd4b62147ad30bab5. Maybe not the details, but the overall idea: linking and initializing is performed on the lower level now. `loadlib`/`freelib` still exists for compatibility reasons, but they does nothing and I'll probably remove them entirely in the future versions.
All on hackage now ([0.1.6](https://hackage.haskell.org/package/curlhs-0.1.6)).

**Comment by nikita-volkov** [comment]
@kkardzis Thanks for the update Krzysztof!
