### ISSUE TITLE
Maybe add support for CURLOPT_HEADERFUNCTION

### ISSUE THREAD

**Issue by jberryman** [kkardzis/curlhs#5]
It's a bit confusing: we can set `CURLOPT_HEADER True` and get the header data sent to our `CURLOPT_WRITEFUNCTION`. And it also looks like I can get the header size from `curl_easy_getinfo curl CURLINFO_HEADER_SIZE`. However the [docs](http://curl.haxx.se/libcurl/c/CURLOPT_HEADER.html) say: 

> When asking to get the header info passed to the same callback as the body, it is not possible to accurately separate them again without detailed knowledge about the protocol in use.
> 
> It is often better to use CURLOPT_HEADERFUNCTION to get the header data separately.

So I wonder how reliable this will be for me, and I also wonder whether `CURLOPT_HEADERFUNCTION` might be more efficient.

Thanks!

**Comment by kkardzis** [comment]
You're right, CURL_HEADERFUNCTION should be there (as well as other callbacks). Bindings are still incomplete unfortunately. I will try to add this option soon, but I cannot promise anything. As time permits.

**Comment by kkardzis** [comment]
`CURLOPT_HEADERFUNCTION` is supported now (try version [0.1.6](https://hackage.haskell.org/package/curlhs-0.1.6) on hackage).

**Comment by jberryman** [comment]
Thanks for adding this so quickly! 

I've decided not to use it for now; here's some background in case it helps others: libcurl (7.38.0) seems to chunk header sections into lines (even if you're not using the header callback) however it doesn't help with parsing multi-line headers (indicated by leading whitespace); [see here](http://stackoverflow.com/q/4580548/176841). So it doesn't simplify parsing sadly.
